### ISSUE TITLE
This is stolen.

### ISSUE THREAD

**Issue by PrimateTerrorVR** [XeonGames-official/Blooket-Hacks#1]
In lines 6, 7 and 8 of the license and I quote: "
* You may not reproduce or distribute any code inside this file without the licenser's permission.
* You may not copy, modify, steal, skid, or recreate any of the code inside this file.
*  You may not under any circumstance republish any code from this file as your own."

This means that you may not copy or modify the code, as such you did.

**Comment by DannyDan0167** [comment]
Hey PrimateTerrorVr, can I see the "paid op" gui you had in your deleted repo: https://github.com/PrimateTerrorVr/blooket-hacks

**Comment by PrimateTerrorVR** [comment]
> Hey PrimateTerrorVr, can I see the "paid op" gui you had in your deleted repo: https://github.com/PrimateTerrorVr/blooket-hacks

No, due to legal reason I had to take it down.

**Comment by PrimateTerrorVR** [comment]
@DannyDan0167 btw ur gimkit cheats are cool.

**Comment by DannyDan0167** [comment]
> @DannyDan0167 btw ur gimkit cheats are cool.

There not really mine, they belong to lazysquid but thank you
